name: workflow-test

# Allows you to run this workflow manually from the Actions tab
on: workflow_dispatch

# Ensure we only have one instance of this workflow running at a time
concurrency: ${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        id: tf-init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        id: tf-plan
        run: terraform plan -no-color
